import { Entity, Column, ManyToOne, JoinColumn, Index } from 'typeorm';
import { ObjectType, Field, Int, registerEnumType } from '@nestjs/graphql';
import { BaseEntity } from './base.entity';
import { Course } from './course.entity';
import { AcademicTerm } from './academic-term.entity';
import { User } from './user.entity';

export enum SectionStatus {
  DRAFT = 'draft',
  ACTIVE = 'active',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
}

export enum EnrollmentMode {
  OPEN = 'open',
  INVITE_ONLY = 'invite_only',
}

registerEnumType(SectionStatus, { name: 'SectionStatus' });
registerEnumType(EnrollmentMode, { name: 'EnrollmentMode' });

@ObjectType()
@Entity('course_sections')
@Index(['courseId'])
@Index(['instructorId'])
@Index(['termId'])
@Index(['enrollmentMode'])
export class CourseSection extends BaseEntity {
  @Field()
  @Column()
  courseId: string;

  @Field(() => Course)
  @ManyToOne(() => Course)
  @JoinColumn({ name: 'courseId' })
  course: Course;

  @Field()
  @Column()
  termId: string;

  @Field(() => AcademicTerm, { nullable: true })
  @ManyToOne(() => AcademicTerm)
  @JoinColumn({ name: 'termId' })
  term: AcademicTerm;

  @Field()
  @Column()
  instructorId: string;

  @Field(() => User)
  @ManyToOne(() => User)
  @JoinColumn({ name: 'instructorId' })
  instructor: User;

  @Field(() => String, { nullable: true })
  @Column({
    type: 'jsonb',
    nullable: true,
    transformer: {
      // TS → DB: parse JSON string to object for JSONB storage
      to: (v: string | null) => (v ? JSON.parse(v) : null),
      // DB → TS: serialize the JSONB object to a JSON string for GraphQL
      from: (v: Record<string, unknown> | null) =>
        v ? JSON.stringify(v) : null,
    },
  })
  schedule: string | null;

  @Field({ nullable: true })
  @Column({ type: 'varchar', nullable: true })
  location: string;

  @Field(() => Int, { nullable: true })
  @Column({ type: 'int', nullable: true })
  capacity: number;

  /**
   * ONBOARD-001: Controls how students can enroll in this section.
   * 'open' — any student can self-enroll from the catalog.
   * 'invite_only' — student must enter the section's invite code.
   */
  @Field(() => EnrollmentMode)
  @Column({
    type: 'enum',
    enum: EnrollmentMode,
    default: EnrollmentMode.OPEN,
  })
  enrollmentMode: EnrollmentMode;

  /**
   * ONBOARD-001: 6-character alphanumeric code for invite-only sections.
   * Generated by the instructor, shared with students out-of-band.
   */
  @Field({ nullable: true })
  @Column({ type: 'varchar', length: 6, nullable: true })
  inviteCode: string;

  /**
   * ONBOARD-001: If true, enrollment requests are auto-approved.
   * If false, instructor must manually approve each enrollment.
   */
  @Field()
  @Column({ type: 'boolean', default: true })
  autoApprove: boolean;

  @Field(() => SectionStatus)
  @Column({
    type: 'enum',
    enum: SectionStatus,
    default: SectionStatus.DRAFT,
  })
  status: SectionStatus;
}
